version: '3.8'
services:
  web:
    image: web_image:latest
    ports:
      - target: 3000
        published: 3000
    deploy:
      replicas: 2
    networks:
      - stacknet

  nginx:
    image: mynginx:latest
    environment:
      - CERTBOT_EMAIL=c.seakmeng0603@gmail.com
      - STAGING=1
      - DEBUG=1
      - USE_LOCAL_CA=1
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - stacknet
    depends_on:
      - web


networks:
  stacknet:
    external: true